AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    eventor fastAPI aws lambda example
Resources:
    EventorLambda:
        Type: AWS::Serverless::Function
        Properties:
            Environment:
                Variables:
                    DB_URI: postgresql://eventor:eventor_s6@eventor.ctafcc3bhwfo.eu-central-1.rds.amazonaws.com:5432/eventorusers
                    SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
                    ALGORITHM: HS256
                    ACCESS_TOKEN_EXPIRE_MINUTES: 30
            FunctionName: eventor-users-ms
            CodeUri: ./
            Handler: app.main.handler
            Runtime: python3.9
            Timeout: 300 # timeout of your lambda function
            MemorySize: 128 # memory size of your lambda function
            Description: eventor users ms
            # other options, see ->
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambdaRole
