name: Build App & Linting Test
on: push

jobs:
  build:
    name: Build App & Linting Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check formatting
        run: |
          isort -c .
      - name: Build Docker image
        run: docker build --file Dockerfile .
